name: Update Version

on:
  registry_package:
    types: [published]

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/yaml-patch
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "[skip ci] update image tag"
        git push
